version: '3'

networks:
  keycloak_network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: keycloak_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: KEYCLOAKDB
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
    ports:
      - "3308:3306/tcp"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ../docker/mysql/conf:/docker-entrypoint-initdb.d
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak_mysql:3306/KEYCLOAKDB
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/server.key
      KC_HTTPS_TRUSTSTORE_FILE: /etc/x509/https/ca.crt
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/etc/x509/https
      - ./keycloak:/app
    entrypoint: ["/bin/sh", "-c"]
    command: ["/app/entrypoint.sh"]
    depends_on:
      - mysql
    networks:
      - keycloak_network

volumes:
  mysql_data:
