CREATE DATABASE IF NOT EXISTS KEYCLOAKDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
DROP USER IF EXISTS 'keycloak'@'%';
CREATE USER 'keycloak'@'%' IDENTIFIED BY 'keycloakpassword';
GRANT ALL PRIVILEGES ON KEYCLOAKDB.* TO 'keycloak'@'%';
FLUSH PRIVILEGES;
